version: "3"

services:
  
  db:
    image: postgres:latest
    container_name: poc_multitenancy_db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: 'multi_tenant'
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    restart: always
    volumes:
      - multi_tenant_db:/var/lib/postgresql/data
    
volumes:
  multi_tenant_db: